apiVersion: v1
kind: Service
metadata:
  name: bmi-app-service
spec:
  selector:
    app: bmi-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
